
before_script:
  - curl -LO https://releases.rancher.com/cli/v0.6.2/rancher-linux-amd64-v0.6.2.tar.gz
  - tar zxf rancher-linux-amd64-v0.6.2.tar.gz
  
build_test:
  script:
    - mkdir -p share
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/colon-cleanout/glam/2020-04-23-colon-cleanout/2020-04-23-colon-cleanout-Colon_Cleanout_Interval_host_subject_id.Colon_Cleanout_Interval.corncob.index.hdf5 share/
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/underfeeding/glam/2020-06-14-underfeeding/2020-06-14-underfeeding-host_subject_id_host_diet.host_subject_id_host_diet.corncob.index.hdf5 share/
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/oca/glam/2020-05-05-OCA/2020-05-05-OCA-participant_day.participant_day.corncob.index.hdf5 share/
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/manifests/2020-07-16-1-manifest.json share/manifest.json
    - docker build -t dockerimages.fhcrc.org/glam:latest .
    - rm -rf share/
    - echo write some unit tests
  
  
deploy:
  only:
    refs:
       - deployment # TODO FIXME change to master at some point
  script:
    - docker login --username $DOCKERIMAGES_USER --password $DOCKERIMAGES_PASS https://dockerimages.fhcrc.org
    - docker push dockerimages.fhcrc.org/glam:latest
    - sleep 15
    - rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY --secret-key $RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack glam --file docker-compose.yml --rancher-file rancher-compose.yml
  
