
before_script:
  - curl -LO https://releases.rancher.com/cli/v0.6.2/rancher-linux-amd64-v0.6.2.tar.gz
  - tar zxf rancher-linux-amd64-v0.6.2.tar.gz
  
build_test:
  script:
    # build/test private version
    - mkdir -p share
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/manifests/2020-08-11-1-mri-manifest.csv .
    - for i in $(cat 2020-08-11-1-mri-manifest.csv | cut -d ',' -f 1); do aws s3 cp $i share/ ; done
    - docker build --build-arg GTM_CONTAINER=$GTM_CONTAINER -t 458818213009.dkr.ecr.us-west-2.amazonaws.com/glam:latest .
    - docker-compose up -d
    - sleep 25
    - curl -I http://localhost:8050 | grep -q "HTTP/1.1 200 OK"
    - docker-compose down
    - rm -rf share/
    - rm 2020-08-11-1-mri-manifest.csv
    # build/test public version 
    - mkdir -p share
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/manifests/2020-08-11-1-demo-manifest.csv .
    - for i in $(cat 2020-08-11-1-demo-manifest.csv | cut -d ',' -f 1); do aws s3 cp $i share/ ; done
    - docker build --build-arg GTM_CONTAINER=$GTM_CONTAINER -t 458818213009.dkr.ecr.us-west-2.amazonaws.com/glam-public:latest .
    - docker-compose -f fhpublic-docker-compose.yml up -d
    - sleep 25
    - curl -I http://localhost:8050 | grep -q "HTTP/1.1 200 OK"
    - docker-compose down
    - rm -rf share/
    - rm 2020-08-11-1-demo-manifest.csv
  
  
deploy:
  stage: deploy
  only:
    refs:
       - deployment # TODO FIXME change to master at some point
  script:
    - AWS_ACCESS_KEY_ID=$ECR_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$ECR_SECRET_KEY AWS_DEFAULT_REGION=$ECR_REGION aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 458818213009.dkr.ecr.us-west-2.amazonaws.com
    - docker push 458818213009.dkr.ecr.us-west-2.amazonaws.com/glam:latest
    - docker push 458818213009.dkr.ecr.us-west-2.amazonaws.com/glam-publica:latest
    - sleep 15
    # push private version
    - rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY --secret-key $RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack glam --file docker-compose.yml --rancher-file rancher-compose.yml
    - sleep 3
    # push public version
    - rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY_PUBLIC --secret-key $RANCHERAPI_SECRET_PUBLIC up -d --pull --force-upgrade --confirm-upgrade --stack glam --file fhpublic-docker-compose.yml --rancher-file rancher-compose.yml
  
