
before_script:
  - curl -LO https://releases.rancher.com/cli/v0.6.2/rancher-linux-amd64-v0.6.2.tar.gz
  - tar zxf rancher-linux-amd64-v0.6.2.tar.gz
  
build_test:
  script:
    - mkdir -p share
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/underfeeding/glam/2020-06-14-underfeeding/2020-06-14-underfeeding-host_diet.host_diet.corncob.index.hdf5 share/
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/oca/glam/2020-05-05-OCA/2020-05-05-OCA-day.day.corncob.index.hdf5 share/
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/crc/glam/2020-06-18-Yachida/2020-06-18-Yachida.results.index.hdf5 share/
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/gvhd/glam/2020-05-08-GVHD/2020-07-09-GVHD-corncob.sampleGroup_log10_MAIT_per_ul_day60_log10_Treg_per_ul_day60.corncob.index.hdf5 share/
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/hosting/kublin/POPs/2020-07-01-POPs-geneshot.index.hdf5 share/
    - aws s3 cp s3://fh-poc-minot-s-mri-geneshot/manifests/2020-07-23-1-manifest.json share/manifest.json
    - docker build -t 458818213009.dkr.ecr.us-west-2.amazonaws.com/glam:latest .
    - docker-compose up -d
    - sleep 25
    - curl -I http://localhost:8050 | grep -q "HTTP/1.1 200 OK"
    - docker-compose down
    - rm -rf share/
  
  
deploy:
  only:
    refs:
       - deployment # TODO FIXME change to master at some point
  script:
    - AWS_ACCESS_KEY_ID=$ECR_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$ECR_SECRET_KEY AWS_DEFAULT_REGION=$ECR_REGION aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 458818213009.dkr.ecr.us-west-2.amazonaws.com
    - docker push 458818213009.dkr.ecr.us-west-2.amazonaws.com/glam:latest
    - sleep 15
    - rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY --secret-key $RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack glam --file docker-compose.yml --rancher-file rancher-compose.yml
  
