version: '2'
services:
  glam:
    ports:
      - "8050:8050"
    image: 458818213009.dkr.ecr.us-west-2.amazonaws.com/glam-public:latest

    labels:
      io.rancher.container.pull_image: always

    restart: always
    environment:
      REDIS_URL: "redis://redis:6379"

  redis:
    image: redis:latest
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
