name: Test Indexing

on: [push, pull_request]  

jobs:

  index:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
      NXF_VER: 20.04.1
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name:  Download geneshot results
        run: |
          curl -s -L https://github.com/Golob-Minot/geneshot/releases/download/v0.6.3/geneshot.results.tar.gz --output geneshot.results.tar.gz && tar xzf geneshot.results.tar.gz
      - name:  Index geneshot results
        run: |
          nextflow run index.nf -profile testing --input output/geneshot.results.hdf5 --output_folder ./ --output_prefix glam -with-docker ubuntu:latest
